# Generated by Django 5.2.6 on 2025-09-27 17:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Book Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.BigIntegerField(
                        help_text="ISBN or Book ID from original data", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                ("authors", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("published_date", models.DateField()),
                (
                    "distribution_expense",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total distribution cost for this book",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.bookcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
